// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateAccountOKCode is the HTTP code returned for type CreateAccountOK
const CreateAccountOKCode int = 200

/*CreateAccountOK successful operation

swagger:response createAccountOK
*/
type CreateAccountOK struct {

	/*
	  In: Body
	*/
	Payload *CreateAccountOKBody `json:"body,omitempty"`
}

// NewCreateAccountOK creates CreateAccountOK with default headers values
func NewCreateAccountOK() *CreateAccountOK {

	return &CreateAccountOK{}
}

// WithPayload adds the payload to the create account o k response
func (o *CreateAccountOK) WithPayload(payload *CreateAccountOKBody) *CreateAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account o k response
func (o *CreateAccountOK) SetPayload(payload *CreateAccountOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountBadRequestCode is the HTTP code returned for type CreateAccountBadRequest
const CreateAccountBadRequestCode int = 400

/*CreateAccountBadRequest Invalid data supplied

swagger:response createAccountBadRequest
*/
type CreateAccountBadRequest struct {
}

// NewCreateAccountBadRequest creates CreateAccountBadRequest with default headers values
func NewCreateAccountBadRequest() *CreateAccountBadRequest {

	return &CreateAccountBadRequest{}
}

// WriteResponse to the client
func (o *CreateAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateAccountNotFoundCode is the HTTP code returned for type CreateAccountNotFound
const CreateAccountNotFoundCode int = 404

/*CreateAccountNotFound Resource doesn't exist

swagger:response createAccountNotFound
*/
type CreateAccountNotFound struct {
}

// NewCreateAccountNotFound creates CreateAccountNotFound with default headers values
func NewCreateAccountNotFound() *CreateAccountNotFound {

	return &CreateAccountNotFound{}
}

// WriteResponse to the client
func (o *CreateAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CreateAccountInternalServerErrorCode is the HTTP code returned for type CreateAccountInternalServerError
const CreateAccountInternalServerErrorCode int = 500

/*CreateAccountInternalServerError Error Internal Server

swagger:response createAccountInternalServerError
*/
type CreateAccountInternalServerError struct {
}

// NewCreateAccountInternalServerError creates CreateAccountInternalServerError with default headers values
func NewCreateAccountInternalServerError() *CreateAccountInternalServerError {

	return &CreateAccountInternalServerError{}
}

// WriteResponse to the client
func (o *CreateAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
