// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ccamaleon5/SaludChainClient/models"
)

// ShareMedicalRecordOKCode is the HTTP code returned for type ShareMedicalRecordOK
const ShareMedicalRecordOKCode int = 200

/*ShareMedicalRecordOK successful operation

swagger:response shareMedicalRecordOK
*/
type ShareMedicalRecordOK struct {

	/*
	  In: Body
	*/
	Payload *models.Credential `json:"body,omitempty"`
}

// NewShareMedicalRecordOK creates ShareMedicalRecordOK with default headers values
func NewShareMedicalRecordOK() *ShareMedicalRecordOK {

	return &ShareMedicalRecordOK{}
}

// WithPayload adds the payload to the share medical record o k response
func (o *ShareMedicalRecordOK) WithPayload(payload *models.Credential) *ShareMedicalRecordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the share medical record o k response
func (o *ShareMedicalRecordOK) SetPayload(payload *models.Credential) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShareMedicalRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ShareMedicalRecordBadRequestCode is the HTTP code returned for type ShareMedicalRecordBadRequest
const ShareMedicalRecordBadRequestCode int = 400

/*ShareMedicalRecordBadRequest Invalid data supplied

swagger:response shareMedicalRecordBadRequest
*/
type ShareMedicalRecordBadRequest struct {
}

// NewShareMedicalRecordBadRequest creates ShareMedicalRecordBadRequest with default headers values
func NewShareMedicalRecordBadRequest() *ShareMedicalRecordBadRequest {

	return &ShareMedicalRecordBadRequest{}
}

// WriteResponse to the client
func (o *ShareMedicalRecordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ShareMedicalRecordNotFoundCode is the HTTP code returned for type ShareMedicalRecordNotFound
const ShareMedicalRecordNotFoundCode int = 404

/*ShareMedicalRecordNotFound Resource doesn't exist

swagger:response shareMedicalRecordNotFound
*/
type ShareMedicalRecordNotFound struct {
}

// NewShareMedicalRecordNotFound creates ShareMedicalRecordNotFound with default headers values
func NewShareMedicalRecordNotFound() *ShareMedicalRecordNotFound {

	return &ShareMedicalRecordNotFound{}
}

// WriteResponse to the client
func (o *ShareMedicalRecordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ShareMedicalRecordInternalServerErrorCode is the HTTP code returned for type ShareMedicalRecordInternalServerError
const ShareMedicalRecordInternalServerErrorCode int = 500

/*ShareMedicalRecordInternalServerError Error Internal Server

swagger:response shareMedicalRecordInternalServerError
*/
type ShareMedicalRecordInternalServerError struct {
}

// NewShareMedicalRecordInternalServerError creates ShareMedicalRecordInternalServerError with default headers values
func NewShareMedicalRecordInternalServerError() *ShareMedicalRecordInternalServerError {

	return &ShareMedicalRecordInternalServerError{}
}

// WriteResponse to the client
func (o *ShareMedicalRecordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
