// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi SaludChain APIs
This is a SaludChain Client that send transactions to SaludChain Blockchain

SaludChain Client exposes APIs to be consume by patients, clinics, insurances, pharmacies and health institutions

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
    Host: localhost:8000
    BasePath: /v1
    Version: 0.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <adriancc5.5@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
