// Code generated by go-swagger; DO NOT EDIT.

package pharmacy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VerifyRecipeOKCode is the HTTP code returned for type VerifyRecipeOK
const VerifyRecipeOKCode int = 200

/*VerifyRecipeOK successful operation

swagger:response verifyRecipeOK
*/
type VerifyRecipeOK struct {
}

// NewVerifyRecipeOK creates VerifyRecipeOK with default headers values
func NewVerifyRecipeOK() *VerifyRecipeOK {

	return &VerifyRecipeOK{}
}

// WriteResponse to the client
func (o *VerifyRecipeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// VerifyRecipeBadRequestCode is the HTTP code returned for type VerifyRecipeBadRequest
const VerifyRecipeBadRequestCode int = 400

/*VerifyRecipeBadRequest invalid hash recipe supplied

swagger:response verifyRecipeBadRequest
*/
type VerifyRecipeBadRequest struct {
}

// NewVerifyRecipeBadRequest creates VerifyRecipeBadRequest with default headers values
func NewVerifyRecipeBadRequest() *VerifyRecipeBadRequest {

	return &VerifyRecipeBadRequest{}
}

// WriteResponse to the client
func (o *VerifyRecipeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// VerifyRecipeNotFoundCode is the HTTP code returned for type VerifyRecipeNotFound
const VerifyRecipeNotFoundCode int = 404

/*VerifyRecipeNotFound health credential doens't exist

swagger:response verifyRecipeNotFound
*/
type VerifyRecipeNotFound struct {
}

// NewVerifyRecipeNotFound creates VerifyRecipeNotFound with default headers values
func NewVerifyRecipeNotFound() *VerifyRecipeNotFound {

	return &VerifyRecipeNotFound{}
}

// WriteResponse to the client
func (o *VerifyRecipeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// VerifyRecipeInternalServerErrorCode is the HTTP code returned for type VerifyRecipeInternalServerError
const VerifyRecipeInternalServerErrorCode int = 500

/*VerifyRecipeInternalServerError error internal server

swagger:response verifyRecipeInternalServerError
*/
type VerifyRecipeInternalServerError struct {
}

// NewVerifyRecipeInternalServerError creates VerifyRecipeInternalServerError with default headers values
func NewVerifyRecipeInternalServerError() *VerifyRecipeInternalServerError {

	return &VerifyRecipeInternalServerError{}
}

// WriteResponse to the client
func (o *VerifyRecipeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
