// Code generated by go-swagger; DO NOT EDIT.

package pharmacy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVerifyRecipeParams creates a new VerifyRecipeParams object
// no default values defined in spec.
func NewVerifyRecipeParams() VerifyRecipeParams {

	return VerifyRecipeParams{}
}

// VerifyRecipeParams contains all the bound params for the verify recipe operation
// typically these are obtained from a http.Request
//
// swagger:parameters verifyRecipe
type VerifyRecipeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the hashCredential that should be validated
	  Required: true
	  In: path
	*/
	HashRecipe string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewVerifyRecipeParams() beforehand.
func (o *VerifyRecipeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHashRecipe, rhkHashRecipe, _ := route.Params.GetOK("hashRecipe")
	if err := o.bindHashRecipe(rHashRecipe, rhkHashRecipe, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHashRecipe binds and validates parameter HashRecipe from path.
func (o *VerifyRecipeParams) bindHashRecipe(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.HashRecipe = raw

	return nil
}
