// Code generated by go-swagger; DO NOT EDIT.

package insurance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ccamaleon5/SaludChainClient/models"
)

// NewCreateDoctorCredentialParams creates a new CreateDoctorCredentialParams object
// no default values defined in spec.
func NewCreateDoctorCredentialParams() CreateDoctorCredentialParams {

	return CreateDoctorCredentialParams{}
}

// CreateDoctorCredentialParams contains all the bound params for the create doctor credential operation
// typically these are obtained from a http.Request
//
// swagger:parameters createDoctorCredential
type CreateDoctorCredentialParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Created Doctor health credential object
	  Required: true
	  In: body
	*/
	Body *models.CredentialSubject
	/*Doctor Id Account
	  Required: true
	  In: header
	*/
	IDAccount string
	/*The Doctor's public key
	  Required: true
	  In: header
	*/
	PublicKey string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateDoctorCredentialParams() beforehand.
func (o *CreateDoctorCredentialParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CredentialSubject
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	if err := o.bindIDAccount(r.Header[http.CanonicalHeaderKey("idAccount")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindPublicKey(r.Header[http.CanonicalHeaderKey("publicKey")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIDAccount binds and validates parameter IDAccount from header.
func (o *CreateDoctorCredentialParams) bindIDAccount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("idAccount", "header")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("idAccount", "header", raw); err != nil {
		return err
	}

	o.IDAccount = raw

	return nil
}

// bindPublicKey binds and validates parameter PublicKey from header.
func (o *CreateDoctorCredentialParams) bindPublicKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("publicKey", "header")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("publicKey", "header", raw); err != nil {
		return err
	}

	o.PublicKey = raw

	return nil
}
