// Code generated by go-swagger; DO NOT EDIT.

package insurance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ccamaleon5/SaludChainClient/models"
)

// GetHealthCredentialByIDOKCode is the HTTP code returned for type GetHealthCredentialByIDOK
const GetHealthCredentialByIDOKCode int = 200

/*GetHealthCredentialByIDOK successful operation

swagger:response getHealthCredentialByIdOK
*/
type GetHealthCredentialByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Credential `json:"body,omitempty"`
}

// NewGetHealthCredentialByIDOK creates GetHealthCredentialByIDOK with default headers values
func NewGetHealthCredentialByIDOK() *GetHealthCredentialByIDOK {

	return &GetHealthCredentialByIDOK{}
}

// WithPayload adds the payload to the get health credential by Id o k response
func (o *GetHealthCredentialByIDOK) WithPayload(payload *models.Credential) *GetHealthCredentialByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health credential by Id o k response
func (o *GetHealthCredentialByIDOK) SetPayload(payload *models.Credential) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthCredentialByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHealthCredentialByIDBadRequestCode is the HTTP code returned for type GetHealthCredentialByIDBadRequest
const GetHealthCredentialByIDBadRequestCode int = 400

/*GetHealthCredentialByIDBadRequest Invalid credential Id supplied

swagger:response getHealthCredentialByIdBadRequest
*/
type GetHealthCredentialByIDBadRequest struct {
}

// NewGetHealthCredentialByIDBadRequest creates GetHealthCredentialByIDBadRequest with default headers values
func NewGetHealthCredentialByIDBadRequest() *GetHealthCredentialByIDBadRequest {

	return &GetHealthCredentialByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetHealthCredentialByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetHealthCredentialByIDNotFoundCode is the HTTP code returned for type GetHealthCredentialByIDNotFound
const GetHealthCredentialByIDNotFoundCode int = 404

/*GetHealthCredentialByIDNotFound ID not found

swagger:response getHealthCredentialByIdNotFound
*/
type GetHealthCredentialByIDNotFound struct {
}

// NewGetHealthCredentialByIDNotFound creates GetHealthCredentialByIDNotFound with default headers values
func NewGetHealthCredentialByIDNotFound() *GetHealthCredentialByIDNotFound {

	return &GetHealthCredentialByIDNotFound{}
}

// WriteResponse to the client
func (o *GetHealthCredentialByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetHealthCredentialByIDInternalServerErrorCode is the HTTP code returned for type GetHealthCredentialByIDInternalServerError
const GetHealthCredentialByIDInternalServerErrorCode int = 500

/*GetHealthCredentialByIDInternalServerError Error Internal Server

swagger:response getHealthCredentialByIdInternalServerError
*/
type GetHealthCredentialByIDInternalServerError struct {
}

// NewGetHealthCredentialByIDInternalServerError creates GetHealthCredentialByIDInternalServerError with default headers values
func NewGetHealthCredentialByIDInternalServerError() *GetHealthCredentialByIDInternalServerError {

	return &GetHealthCredentialByIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetHealthCredentialByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
