// Code generated by go-swagger; DO NOT EDIT.

package insurance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHealthCredentialByIDParams creates a new GetHealthCredentialByIDParams object
// no default values defined in spec.
func NewGetHealthCredentialByIDParams() GetHealthCredentialByIDParams {

	return GetHealthCredentialByIDParams{}
}

// GetHealthCredentialByIDParams contains all the bound params for the get health credential by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getHealthCredentialById
type GetHealthCredentialByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the patient's digital identity public key.
	  Required: true
	  In: path
	*/
	PublicKey string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetHealthCredentialByIDParams() beforehand.
func (o *GetHealthCredentialByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPublicKey, rhkPublicKey, _ := route.Params.GetOK("publicKey")
	if err := o.bindPublicKey(rPublicKey, rhkPublicKey, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPublicKey binds and validates parameter PublicKey from path.
func (o *GetHealthCredentialByIDParams) bindPublicKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PublicKey = raw

	return nil
}
