// Code generated by go-swagger; DO NOT EDIT.

package insurance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VerifyHealthCredentialOKCode is the HTTP code returned for type VerifyHealthCredentialOK
const VerifyHealthCredentialOKCode int = 200

/*VerifyHealthCredentialOK successful operation

swagger:response verifyHealthCredentialOK
*/
type VerifyHealthCredentialOK struct {
}

// NewVerifyHealthCredentialOK creates VerifyHealthCredentialOK with default headers values
func NewVerifyHealthCredentialOK() *VerifyHealthCredentialOK {

	return &VerifyHealthCredentialOK{}
}

// WriteResponse to the client
func (o *VerifyHealthCredentialOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// VerifyHealthCredentialBadRequestCode is the HTTP code returned for type VerifyHealthCredentialBadRequest
const VerifyHealthCredentialBadRequestCode int = 400

/*VerifyHealthCredentialBadRequest invalid health credential supplied

swagger:response verifyHealthCredentialBadRequest
*/
type VerifyHealthCredentialBadRequest struct {
}

// NewVerifyHealthCredentialBadRequest creates VerifyHealthCredentialBadRequest with default headers values
func NewVerifyHealthCredentialBadRequest() *VerifyHealthCredentialBadRequest {

	return &VerifyHealthCredentialBadRequest{}
}

// WriteResponse to the client
func (o *VerifyHealthCredentialBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// VerifyHealthCredentialNotFoundCode is the HTTP code returned for type VerifyHealthCredentialNotFound
const VerifyHealthCredentialNotFoundCode int = 404

/*VerifyHealthCredentialNotFound health credential doens't exist

swagger:response verifyHealthCredentialNotFound
*/
type VerifyHealthCredentialNotFound struct {
}

// NewVerifyHealthCredentialNotFound creates VerifyHealthCredentialNotFound with default headers values
func NewVerifyHealthCredentialNotFound() *VerifyHealthCredentialNotFound {

	return &VerifyHealthCredentialNotFound{}
}

// WriteResponse to the client
func (o *VerifyHealthCredentialNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// VerifyHealthCredentialInternalServerErrorCode is the HTTP code returned for type VerifyHealthCredentialInternalServerError
const VerifyHealthCredentialInternalServerErrorCode int = 500

/*VerifyHealthCredentialInternalServerError error internal server

swagger:response verifyHealthCredentialInternalServerError
*/
type VerifyHealthCredentialInternalServerError struct {
}

// NewVerifyHealthCredentialInternalServerError creates VerifyHealthCredentialInternalServerError with default headers values
func NewVerifyHealthCredentialInternalServerError() *VerifyHealthCredentialInternalServerError {

	return &VerifyHealthCredentialInternalServerError{}
}

// WriteResponse to the client
func (o *VerifyHealthCredentialInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
