// Code generated by go-swagger; DO NOT EDIT.

package insurance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVerifyHealthCredentialParams creates a new VerifyHealthCredentialParams object
// no default values defined in spec.
func NewVerifyHealthCredentialParams() VerifyHealthCredentialParams {

	return VerifyHealthCredentialParams{}
}

// VerifyHealthCredentialParams contains all the bound params for the verify health credential operation
// typically these are obtained from a http.Request
//
// swagger:parameters verifyHealthCredential
type VerifyHealthCredentialParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the hashCredential that should be validated
	  Required: true
	  In: path
	*/
	HashCredential string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewVerifyHealthCredentialParams() beforehand.
func (o *VerifyHealthCredentialParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHashCredential, rhkHashCredential, _ := route.Params.GetOK("hashCredential")
	if err := o.bindHashCredential(rHashCredential, rhkHashCredential, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHashCredential binds and validates parameter HashCredential from path.
func (o *VerifyHealthCredentialParams) bindHashCredential(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.HashCredential = raw

	return nil
}
