// Code generated by go-swagger; DO NOT EDIT.

package clinic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BookNewMedicalAppointmentHandlerFunc turns a function with the right signature into a book new medical appointment handler
type BookNewMedicalAppointmentHandlerFunc func(BookNewMedicalAppointmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookNewMedicalAppointmentHandlerFunc) Handle(params BookNewMedicalAppointmentParams) middleware.Responder {
	return fn(params)
}

// BookNewMedicalAppointmentHandler interface for that can handle valid book new medical appointment params
type BookNewMedicalAppointmentHandler interface {
	Handle(BookNewMedicalAppointmentParams) middleware.Responder
}

// NewBookNewMedicalAppointment creates a new http.Handler for the book new medical appointment operation
func NewBookNewMedicalAppointment(ctx *middleware.Context, handler BookNewMedicalAppointmentHandler) *BookNewMedicalAppointment {
	return &BookNewMedicalAppointment{Context: ctx, Handler: handler}
}

/*BookNewMedicalAppointment swagger:route POST /clinic/medicalappointment/create clinic bookNewMedicalAppointment

Create New Medical Appointment

This service is responsible for book a medical appointment, that through multi signature contract, how proof blockchain generates a credential about this contract to share information with clinic

*/
type BookNewMedicalAppointment struct {
	Context *middleware.Context
	Handler BookNewMedicalAppointmentHandler
}

func (o *BookNewMedicalAppointment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookNewMedicalAppointmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
