// Code generated by go-swagger; DO NOT EDIT.

package clinic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BookMedicalAppointmentHandlerFunc turns a function with the right signature into a book medical appointment handler
type BookMedicalAppointmentHandlerFunc func(BookMedicalAppointmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookMedicalAppointmentHandlerFunc) Handle(params BookMedicalAppointmentParams) middleware.Responder {
	return fn(params)
}

// BookMedicalAppointmentHandler interface for that can handle valid book medical appointment params
type BookMedicalAppointmentHandler interface {
	Handle(BookMedicalAppointmentParams) middleware.Responder
}

// NewBookMedicalAppointment creates a new http.Handler for the book medical appointment operation
func NewBookMedicalAppointment(ctx *middleware.Context, handler BookMedicalAppointmentHandler) *BookMedicalAppointment {
	return &BookMedicalAppointment{Context: ctx, Handler: handler}
}

/*BookMedicalAppointment swagger:route POST /clinic/medicalappointment clinic bookMedicalAppointment

Create Medical Appointment

This service is responsible for book a medical appointment, that through multi signature contract, how proof blockchain generates a credential about this contract to share information with clinic

*/
type BookMedicalAppointment struct {
	Context *middleware.Context
	Handler BookMedicalAppointmentHandler
}

func (o *BookMedicalAppointment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookMedicalAppointmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
