// Code generated by go-swagger; DO NOT EDIT.

package clinic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ccamaleon5/SaludChainClient/models"
)

// SetMedicalAttentionOKCode is the HTTP code returned for type SetMedicalAttentionOK
const SetMedicalAttentionOKCode int = 200

/*SetMedicalAttentionOK successful operation

swagger:response setMedicalAttentionOK
*/
type SetMedicalAttentionOK struct {

	/*
	  In: Body
	*/
	Payload *models.Credential `json:"body,omitempty"`
}

// NewSetMedicalAttentionOK creates SetMedicalAttentionOK with default headers values
func NewSetMedicalAttentionOK() *SetMedicalAttentionOK {

	return &SetMedicalAttentionOK{}
}

// WithPayload adds the payload to the set medical attention o k response
func (o *SetMedicalAttentionOK) WithPayload(payload *models.Credential) *SetMedicalAttentionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set medical attention o k response
func (o *SetMedicalAttentionOK) SetPayload(payload *models.Credential) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetMedicalAttentionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SetMedicalAttentionBadRequestCode is the HTTP code returned for type SetMedicalAttentionBadRequest
const SetMedicalAttentionBadRequestCode int = 400

/*SetMedicalAttentionBadRequest Invalid data supplied

swagger:response setMedicalAttentionBadRequest
*/
type SetMedicalAttentionBadRequest struct {
}

// NewSetMedicalAttentionBadRequest creates SetMedicalAttentionBadRequest with default headers values
func NewSetMedicalAttentionBadRequest() *SetMedicalAttentionBadRequest {

	return &SetMedicalAttentionBadRequest{}
}

// WriteResponse to the client
func (o *SetMedicalAttentionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SetMedicalAttentionNotFoundCode is the HTTP code returned for type SetMedicalAttentionNotFound
const SetMedicalAttentionNotFoundCode int = 404

/*SetMedicalAttentionNotFound Resource doesn't exist

swagger:response setMedicalAttentionNotFound
*/
type SetMedicalAttentionNotFound struct {
}

// NewSetMedicalAttentionNotFound creates SetMedicalAttentionNotFound with default headers values
func NewSetMedicalAttentionNotFound() *SetMedicalAttentionNotFound {

	return &SetMedicalAttentionNotFound{}
}

// WriteResponse to the client
func (o *SetMedicalAttentionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// SetMedicalAttentionInternalServerErrorCode is the HTTP code returned for type SetMedicalAttentionInternalServerError
const SetMedicalAttentionInternalServerErrorCode int = 500

/*SetMedicalAttentionInternalServerError Error Internal Server

swagger:response setMedicalAttentionInternalServerError
*/
type SetMedicalAttentionInternalServerError struct {
}

// NewSetMedicalAttentionInternalServerError creates SetMedicalAttentionInternalServerError with default headers values
func NewSetMedicalAttentionInternalServerError() *SetMedicalAttentionInternalServerError {

	return &SetMedicalAttentionInternalServerError{}
}

// WriteResponse to the client
func (o *SetMedicalAttentionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
