// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AppointmentSubject appointment subject
// swagger:model AppointmentSubject
type AppointmentSubject struct {

	// appointment date
	// Format: date-time
	Date strfmt.DateTime `json:"date,omitempty"`

	// Doctor's hexadecimal public key
	DoctorPublicKey string `json:"doctorPublicKey,omitempty"`

	// Health Credential's hash
	HashHealthCredential string `json:"hashHealthCredential,omitempty"`

	// Patient's hexadecimal public key
	PatientPublicKey string `json:"patientPublicKey,omitempty"`
}

// Validate validates this appointment subject
func (m *AppointmentSubject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppointmentSubject) validateDate(formats strfmt.Registry) error {

	if swag.IsZero(m.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppointmentSubject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppointmentSubject) UnmarshalBinary(b []byte) error {
	var res AppointmentSubject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
