// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MedicalAttention medical attention
// swagger:model MedicalAttention
type MedicalAttention struct {

	// Doctor's hexadecimal public key
	DoctorPublicKey string `json:"doctorPublicKey,omitempty"`

	// Doctor's Health Credential hash
	HashHealthCredential string `json:"hashHealthCredential,omitempty"`

	// Medical record about this medical appointment
	MedicalRecord string `json:"medicalRecord,omitempty"`

	// Patient's hexadecimal public key
	PatientPublicKey string `json:"patientPublicKey,omitempty"`

	// Recipe given by doctor to patient
	Recipe string `json:"recipe,omitempty"`
}

// Validate validates this medical attention
func (m *MedicalAttention) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MedicalAttention) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MedicalAttention) UnmarshalBinary(b []byte) error {
	var res MedicalAttention
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
