// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MedicalAttention medical attention
// swagger:model MedicalAttention
type MedicalAttention struct {

	// Patient's hexadecimal public key
	MedicalAppointmentID string `json:"medicalAppointmentID,omitempty"`

	// Doctor's PrivateKey
	PublicKey string `json:"publicKey,omitempty"`

	// Record Medical write by doctor
	RecordMedical string `json:"recordMedical,omitempty"`
}

// Validate validates this medical attention
func (m *MedicalAttention) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MedicalAttention) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MedicalAttention) UnmarshalBinary(b []byte) error {
	var res MedicalAttention
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
